### ISSUE TITLE
Error when only r_emailaddress permission is requested

### ISSUE THREAD

**Issue by tolyakir** [SokratisVidros/passport-linkedin-oauth2#3]
In case when only `r_emailaddress` is requested (i.e. no `r_liteprofile`), the following error is returned:

```
{ InternalOAuthError: failed to fetch user profile (status: 403 data: {"serviceErrorCode":100,"message":"Not enough permissions to access: GET /me","status":403
```

It looks like `Strategy.prototype.userProfile` needs to be updated, to check `scope` and request profile and/or email accordingly. Currently, the code assumes that `r_liteprofile` is always granted.

**Comment by tolyakir** [comment]
Another issue is if `scope` is specified in `passport.authenticate()`:
https://gist.github.com/eezhal92/cf6b3892231b4f3c1be4b7055d394283#file-strategy-js-L235

it's not passed to `OAuth2Strategy.prototype._loadUserProfile`:

https://gist.github.com/eezhal92/cf6b3892231b4f3c1be4b7055d394283#file-strategy-js-L363

**Comment by tingham** [comment]
I'm rolling this in and seeing the following (I had to add a console dump for the error @:39)

My app has r_emailaddress and r_liteprofile permissions so I'm not sure what I'm missing. Was there anything else variant about configuring this strategy to get it working?

Thanks

```
{ InternalOAuthError: failed to fetch user profile
    at Strategy.<anonymous> (/Volumes/External/Project/node_modules/@sokratis/passport-linkedin-oauth2/lib/oauth2.js:39:15)
    at passBackControl (/Volumes/External/Project/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/Volumes/External/Project/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:978:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  name: 'InternalOAuthError',
  message: 'failed to fetch user profile',
  oauthError:
   { statusCode: 403,
     data: '{"serviceErrorCode":100,"message":"Not enough permissions to access: GET /me","status":403}' } }
```
